### ISSUE TITLE
how can i change  Language

### ISSUE THREAD

**Issue by jcttq11** [accetto/ubuntu-vnc-xfce#10]

**Comment by accetto** [comment]
Hello,
depending on what you actually need, with this image, it would probably require some modifications in the Dockerfile. Check the **stage-xfce** part please. It's not necessarily the case with the newer images [accetto/xubuntu-vnc](https://hub.docker.com/r/accetto/xubuntu-vnc) or [accetto/xubuntu-vnc-novnc](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc). They both support **sudo**, so you're able to install new stuff also in running containers. It would help, if you'd provide more information.
Regards, accetto

**Comment by accetto** [comment]
I'm closing this question because of the lack of cooperation.
