### ISSUE TITLE
nomachine

### ISSUE THREAD

**Issue by capriciousduck** [accetto/ubuntu-vnc-xfce#12]
Why is nomachine saying "No X server detected"?

**Comment by capriciousduck** [comment]
P.S I installed nomachine after accessing through VNC. Created password for the root account and restarted the nomachine service. But still I got the same error I stated above.

**Comment by accetto** [comment]
Sorry, I didn't tried it with NX yet, so I cannot answer the question at the moment. Have you tested it also with the newer images [accetto/xubuntu-vnc](https://github.com/accetto/xubuntu-vnc) or [accetto/xubuntu-vnc-novnc](https://github.com/accetto/xubuntu-vnc-novnc)?

**Comment by capriciousduck** [comment]
No root user by default in  accetto/xubuntu-vnc-novnc?

**Comment by capriciousduck** [comment]
Nope. Nomachine is not working in "accetto/xubuntu-vnc-novnc" too. Is there any alternative to VNC? I want to run pycharm on my server. My local machine is not too powerful. Any alternative so that I can login via VNC and install the alternate software and continue with my work?

**Comment by capriciousduck** [comment]
The NX says it cannot detect any X server running. XFCE4 is an X server, right?

**Comment by capriciousduck** [comment]
Oh man, I got it working now. This is the command I used. Tried with consol image, and it worked. So I added SYS_PTRACE additionally to the docker command while using your image and I got it working. Don't know why it worked. But I am happy. If you know why it worked, please let me know. Thanks!

**Comment by capriciousduck** [comment]
PS: Oops! This is the command.

`docker run -d --name desktop --restart unless-stopped -p 4800:4800 -e VNC_PW=vncpassword -e VNC_RESOLUTION=1920x1080 -e HOME=/root -p 10000:5901 -p 31415:31415 -p 4000:4000 -p 10001:6901 -v /mnt/sysdisk:/mnt/sysdisk --cap-add=SYS_PTRACE --shm-size 4g accetto/ubuntu-vnc-xfce`

**Comment by accetto** [comment]
> No root user by default in accetto/xubuntu-vnc-novnc?

All [accetto/xubuntu-vnc](https://github.com/accetto/xubuntu-vnc) and [accetto/xubuntu-vnc-novnc](https://github.com/accetto/xubuntu-vnc-novnc) containers run intentionally under a non-root account by default. However, you can easily override that by using the `--user 0:0` or `--user root:root` argument with `docker run`. Please note that the home folder would still be `/home/homeless`, until you explicitely override it by setting the related environment variable.

> Any alternative so that I can login via VNC and install the alternate software and continue with my work?

You can always connect to all containers using any VNC viewer. You can also connect via any web browser to all containers that include noVNC.

All [accetto/xubuntu-vnc](https://github.com/accetto/xubuntu-vnc) and [accetto/xubuntu-vnc-novnc](https://github.com/accetto/xubuntu-vnc-novnc) containers support `sudo`, so you can install any software you wish. The default password for `sudo` is **headless**. If you want to install from Ubuntu's repositories, then do not forget to update them first using `sudo apt-get update`. Please note that [accetto/ubuntu-vnc-xfce](https://github.com/accetto/ubuntu-vnc-xfce) containers **do not** support `sudo`. You have to run them as root to install anything new.

`The NX says it cannot detect any X server running. XFCE4 is an X server, right?`

Not exactly, but it's part of the Xfce4 installation.

I'm glad that you've found a way around. It's kind of a hack, but if it works then it works. :) Only be sure that your environment is secure.

I did a few quick experiments, trying to find some alternatives, but with no success yet, unfortunately. However, I find it interesting, so I think that I'll come to it later, when I'll have more time.

It would help, if you would describe your scenario, what are you trying to achieve and why you don't want to use VNC. Then I could develop some new containers supporting it.

**Comment by capriciousduck** [comment]
I want to run PyCharm on my server since my local machine is less powerful. And I found VNC to be slow to work with pycharm.
