### ISSUE TITLE
How can i setup the machine for novnc/ssl connections

### ISSUE THREAD

**Issue by Sercos10** [accetto/ubuntu-vnc-xfce#15]
I've been trying for a whole week, and i tried my best but i still can't make it, do you have any advice/suggestion/tutorial of how to setup for ssl?
Thank you so much

PD: I'm new so i'm sorry if i asked a silly question.

**Comment by accetto** [comment]
Hello @Sercos10,

thank you for you feedback. Indeed, SSL access is one of the items on my TODO list. However, I'll do it first for my newer images of the third generation (G3).

I'm really sorry, but I do not have any useful tutorials or suggestions currently. I myself need to experiment with it first.

Unfortunatelly, it'll be really hard to spare the time in the near future. I can only promise, that I'll let you know if I'll get something ready. 

Would you not prefer to use one of the newer images?

For example [accetto/ubuntu-vnc-xfce-g3:latest](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-g3) or [accetto/ubuntu-vnc-xfce-g3:20.04](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-g3) 
.
Regards,
accetto

**Comment by Sercos10** [comment]
Thank you so much, for your answer, i will try your newer images
