### ISSUE TITLE
perssist homedir

### ISSUE THREAD

**Issue by etamari** [accetto/ubuntu-vnc-xfce#16]
i want to save homedir so when docker is up its takes my .pycharm .cache .ssh etc
the problem is when i do this docker won't start form few reasons: the pass auth for example. when i solves it by seleting the password in advanced the docker not start and no errors

**Comment by accetto** [comment]
Hello @etamari,

if you really want to persist the complete `$HOME` directory outside the container, then the only solution that works across the environments is using Docker volumes. Using bind mounts can also work under some conditions on some environments, but you have to be sure, that you are able to configure it correctly. There is already the [sibling discussion thread 39](https://github.com/accetto/ubuntu-vnc-xfce-g3/discussions/39) about it.

However, I would recommend not binding the complete `$HOME` directory with Docker containers that provide GUI desktops.

It's better to follow the _application profiles approach_, when you bind application related directories separately.
For example, having a Firefox profile, Visual Studio Code profile etc.

I would also recommend to use my newer images of the third generation (G3), e.g. [accetto/ubuntu-vnc-xfce-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-g3) and others.

Regards,
accetto

**Comment by etamari** [comment]
Thanks a lot for the answer I will try that, and let you know

**Comment by etamari** [comment]
hi accetto, thanks very much for your informative answer, tried on Ubuntu16.04, Ubuntu18.04, Ubuntu20.04
works perfectly. not very easy to find the error, and fix them. but eventually it does what i need it to do.
