### ISSUE TITLE
--wait: /boot/dockerstartup/vnc_startup.sh: Permission denied

### ISSUE THREAD

**Issue by MSandro** [accetto/ubuntu-vnc-xfce#6]
why???

**Comment by accetto** [comment]
Hello MSandro,

thank you for you feedback. I really appreciate it.

You are unfortunatelly right. Something went wrong by the last automated build and I had no idea about it. The lesson is to test *everything* after *each* buid. :(

I doesn't happen by local builds and also the images with Firefox are OK.

I'm looking at it just now and it'll be fixed promptly. :)
Thanks a lot once more.

Cheers
accetto

**Comment by accetto** [comment]
The issue has been fixed in the release 18.06.1. The new images are already available on Docker Hub.
