### ISSUE TITLE
After run the docker image it shows log and not leaving command for us

### ISSUE THREAD

**Issue by DineshGuptaa** [accetto/ubuntu-vnc-xfce#7]
Hi All,

Thanks for this docker image. It helps me a lot.

I am facing one issue. After running the image it not leave command prompt, even after pressing `'enter'` key. If I press the `'ctlr + c'` then come out from running image itself.

	/data/accetto_vnc$ docker run -it --rm  -p6901:6901 min_vnc
	USER_ID: 0, GROUP_ID: 0

	------------------ change VNC password  ------------------

	------------------ start noVNC  ----------------------------

	------------------ start VNC server ------------------------
	remove old vnc locks to be a reattachable container
	start vncserver with param: VNC_COL_DEPTH=24, VNC_RESOLUTION=1280x1024
	...
	start window manager
	...

	------------------ VNC environment started ------------------

	VNCSERVER started on DISPLAY= :1
			=> connect via VNC viewer with 172.17.0.2:5901

	noVNC HTML client started:
			=> connect via http://172.17.0.2:6901/?password=...

Please help me to get the control of command prompt.

Thanks,
Dinesh

**Comment by DineshGuptaa** [comment]
Hi Accetto,
Is there any way to get the command prompt after run docker without - d(detached). For example. 
    docker run -it -p26901:6901 accetto_vnc /bin/bash

I am getting the command prompt in ConSol but while running your docker Not getting command prompt.
Please guide me where I need to change so that command prompt released. 

Thanks

**Comment by accetto** [comment]
Hallo Dinesh,

I have to check it, I've never used it this way. Hopefully I'll find some time this weekend.

Regards
accetto

**Comment by accetto** [comment]
The issue will be fixed in the next release. Expecting to publish it tomorrow.

**Comment by DineshGuptaa** [comment]
Thank for update.

**Comment by accetto** [comment]
Hallo Dinesh,

I've updated the whole image set, so you can use also the other two images ('accetto/ubuntu-vnc-xfce-firefox-default' and 'accetto/ubuntu-vnc-xfce-firefox-plus'). The README files are also updated.

Btw, if you'll find my projects and images useful, you may consider giving them some stars. ;-)

Regards
accetto
