### ISSUE TITLE
Connecting to X Server from another container

### ISSUE THREAD

**Issue by harperaa** [accetto/ubuntu-vnc-xfce#9]
Hello, I have been trying to connect to this container, from another container on the same net, and perform a remote xterm.  I would like to do this, to expose another headless server and present that server's xterm on your server, so it can be viewed through novnc. This will allow me to replace this old unsupported container...https://github.com/psharkey/docker/tree/master/novnc

When I set it up, with your container, I can see the port open: 5901 and vnc works, but it appears the xserver (xfce4) is started in -nolisten tcp mode.  I disabled that in the /etc/X11/xinit/xserverrc file, and started the container, but it still won't allow a remote xterm.  I get "xterm: Xt error: Can't open display: %s" error from remote client, when trying to issue: xterm [IP]:1.  For testing, to ensure it was not an xauthority issue, I gave command xhost + still no connection.  I feel like I am missing something simple, so I thought I would ask, since you know the setup best.  

Could you please assist in how I can configure your container to accept remote xterm commands, which will then present them through the novnc server?

**Comment by accetto** [comment]
Hello,
unfortunatelly I haven't tested this kind of scenario yet. Can you check if you would have the same problems also with the newer container [accetto/xubuntu-vnc-novnc](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc) please?

**Comment by accetto** [comment]
Closing this one because of the lack of cooperation. Probably not required or not an issue any more.
